### PR TITLE
7 implement pdf file split

### LINKED ISSUE #7: Implement pdf file split
Enable the user to split one pdf file into multiple files (at least two)

* Select ranges {(x, y), z} where x and y is a range from page x to page y and z is a single page index. Multiple ranges mean different exported pdf file.

### PR DESCRIPTION
**Pull request by h0p3zZ**

### CODE REVIEW

**Review by MchiFab — COMMENTED** [review]
after successful split export it will not work a 2nd time unless export sting is modified, might not be relevant.

**Comment by h0p3zZ** [comment]
> after successful split export it will not work a 2nd time unless export sting is modified, might not be relevant.

is an issue - will fix this

**Comment by AndreasLeeb** [comment]
IMO the help text for the export page selection suggests that you can enter [...] for all pages (at least I interpreted it that way) but then it cannot be parsed and fails silently.

**Comment by h0p3zZ** [comment]
> IMO the help text for the export page selection suggests that you can enter [...] for all pages (at least I interpreted it that way) but then it cannot be parsed and fails silently.

Changed definition for the task: 
fix  [1-5, singlePage] so the singlePage page is appended as well
throw errors if the format of the exportString is wrong in some way (and do not export any file(s))

Added this to a new issue to rework the feature implementation

**Review by AndreasLeeb — APPROVED** [review]

**Pull request merged**
